name: core_ui
version: 0.0.1
publish_to: none
description: Project Core UI module

environment:
  sdk: ">=3.1.2 <4.1.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  navigation:
    path: ../navigation
  flutter_svg: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - resources/assets/
  fonts:
    - family: Manrope
      fonts:
        - asset: resources/fonts/Manrope-Regular.ttf
        - asset: resources/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: resources/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: resources/fonts/Manrope-ExtraBold.ttf
          weight: 900